name: Building the Java project
on: [workflow_dispatch]
jobs: 
    build-java: 
          runs-on: ubuntu-latest
          steps:
             - name: Checkout Repo
               uses: actions/checkout@v3            
             - name: Setup JDK 
               uses: actions/setup-java@v3
               with:
                   distribution: 'temurin'
                   java-version: '11'
             - name: Build with Maven
               run: mvn clean install 
               
             - run: echo "Build Succesfully..."
              